config/routes.rb
Rails.application.routes.draw do
  resources :shops, only: [:index, :show]
  resources :books, only: [:index] do
    collection do
      get :with_quantity
    end
  end

  root to: "books#index"
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author

  has_many :shops, through: :shop_books
  has_many :shop_books

  scope :order_by_author_name_and_book_id,
    -> { includes(:author).order("authors.name, books.id") }
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  has_many :books, through: :shop_books
  has_many :shop_books
end

app/models/shop_book.rb
class ShopBook < ActiveRecord::Base
  belongs_to :shop
  belongs_to :book

  scope :sum_quantity_per_book, -> { group(:book_id).sum(:quantity) }
  scope :show_shop, -> (shop_id) { includes(:book, book: :author).where(shop_id: shop_id).order("books.title") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.order_by_author_name_and_book_id
  end

  def with_quantity
    book_id_sum_quantity_map = ShopBook.sum_quantity_per_book
    @books_quantities = []

    Book.select([:id, :title]).find_each do |book|
      quantity = book_id_sum_quantity_map.try(:[], book.id) || 0
      @books_quantities << { id: book.id, title: book.title, quantity: quantity }
    end

    @books_quantities.sort_by! { |b| [-b[:quantity], b[:id]] }
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show]

  def index
    @shops = Shop.all
  end

  def show
    @shop_books = ShopBook.show_shop @shop.id
  end

  private
    def set_shop
      @shop = Shop.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/index.html.erb
<h1>Books</h1>

<%= link_to 'home', root_path %>
<br><br>

<table border="1">
  <thead>
    <tr>
      <th>book id</th>
      <th>title</th>
      <th>author</th>
      <th>author id</th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.id %></td>
        <td><%= book.title %></td>
        <td><%= book.author.name %></td>
        <td><%= book.author_id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
ordered by author name and book id.

app/views/books/with_quantity.html.erb
<h1>Books with quantity among all shops</h1>

<%= link_to 'home', root_path %>
<br><br>

<table border="1">
  <thead>
    <tr>
      <th>book id</th>
      <th>title</th>
      <th>quantity</th>
    </tr>
  </thead>

  <tbody>
    <% @books_quantities.each do |book| %>
      <tr>
        <td><%= book[:id] %></td>
        <td><%= book[:title] %></td>
        <td><%= book[:quantity] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
ordered by quantity and book id.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookstore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shops/index.html.erb
<h1>Shops</h1>

<%= link_to 'home', root_path %>
<br><br>

<table>
  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><li><%= link_to shop.name, shop_path(shop) %></li></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shops/show.html.erb
<h1><%= @shop.name %></h1>

<%= link_to 'home', root_path %> >> <%= link_to 'shops', shops_path %>
<br>
<br>

<table border="1">
  <thead>
    <tr>
      <th>id</th>
      <th>title</th>
      <th>author</th>
      <th>author id</th>
      <th>quantity</th>
    </tr>
  </thead>


  <tbody>
    <% @shop_books.each do |shop_book| %>
      <tr>
        <td><%= shop_book.book.id %></td>
        <td><%= shop_book.book.title %></td>
        <td><%= shop_book.book.author.name %></td>
        <td><%= shop_book.book.author.id %></td>
        <td><%= shop_book.quantity %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
ordered by book title